# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userloginreg', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(to='courses.Course')),
                ('user', models.ManyToManyField(to='userloginreg.User')),
            ],
        ),
    ]
